pipeline {
    agent any
    stages {
        stage("System info") {
            steps {
                sh '''
                  docker version
                  docker info
                  docker compose version 
                  curl --version
                '''
            }
        }
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Download data') {
            steps {
                git branch: 'master', url: 'https://github.com/GShabanov/khpi.git'
            }
        }
        stage('Start') {
            steps {
                sh '''
                    #!/bin/bash
                    cd DevOpsPractice
                    cd lab1
                    docker compose up -d --no-color --wait
                    docker compose ps
                '''
            }
        }
    }
    post {
        always {
            sh '''
                #!/bin/bash
                cd DevOpsPractice
                cd lab1
                docker compose down --remove-orphans -v
                docker compose ps
            '''
        }
    }
}
